name: Update Songlist

on:
  schedule:
    - cron: '44 13 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest export.json
        id: check
        run: |
          curl -fL "https://api.streamersonglist.com/v1/streamers/39650/songs/export" -o temp.json
          jq empty temp.json

          if diff -q \
            <(jq -S . temp.json) \
            <(jq -S 'del(._version)' export.json 2>/dev/null || echo '{}') \
            >/dev/null; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "Нет изменений"
            rm temp.json
            exit 0
          fi

          TIMESTAMP=$(date +%s)
          jq --argjson ver "$TIMESTAMP" '. + {"_version": $ver}' temp.json > export.json
          echo "changed=true" >> $GITHUB_OUTPUT
          rm temp.json

      - name: Commit and Push
        if: steps.check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          MSK_TIME=$(TZ='Europe/Moscow' date '+%d.%m.%Y %H:%M')

          git add export.json
          git commit -m "upd $MSK_TIME"
          git push
